# -*- coding: utf-8 -*-
"""Lora_cartoon_418.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yssw5dVnAtPUbXDIIdjhdokiIDFg-gXl

# Step 1: Install the environment
"""

!nvidia-smi
!pip install --upgrade protobuf==5.29.1
!pip install numpy==1.26.0
!pip install wandb==0.16.3
!pip install --upgrade accelerate diffusers[training]
!pip install -q transformers datasets peft bitsandbytes xformers huggingface_hub

"""# Step 2: Upload and check the training data"""

import os
image_dir = "/content/sticker_images"
os.makedirs(image_dir, exist_ok=True)

images = os.listdir(image_dir)
print(f"find {len(images)} picturs：{images[:]}")
if len(images) == 0:
    raise Exception("upload /content/sticker_images first！")

"""# Step 3: Diffusers"""

# Commented out IPython magic to ensure Python compatibility.
import os
os.environ["WANDB_DISABLED"] = "true"
!git clone https://github.com/huggingface/diffusers.git
# %cd /content/diffusers

"""# Step 4: Training Lora"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/diffusers
!pip install -e ".[torch]"
import diffusers

# clean the history
!rm -rf /content/lora_sticker_model

# confirm the parameters
!python examples/dreambooth/train_dreambooth_lora.py \
  --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" \
  --instance_data_dir="/content/sticker_images" \
  --output_dir="/content/lora_sticker_model" \
  --instance_prompt="a sks sticker style" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --learning_rate=1e-4 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=1200 \
  --checkpointing_steps=200 \
  --mixed_precision="fp16" \
  --use_8bit_adam

pip install bitsandbytes

import os
model_dir = "/content/lora_sticker_model"
print("exist?", os.path.exists(model_dir))

"""# Step 5: Testing"""

!pip uninstall -y diffusers
!pip install diffusers[torch] --upgrade

from diffusers import StableDiffusionPipeline
import torch
# loading models
pipe=StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")
pipe.unet.load_attn_procs("/content/lora_sticker_model")
# pipe.unet.load_attn_procs("/content/lora_sticker_model/checkpoint-400")
# generating pictures
animal = "cat"
prompt = f"a sks {animal} sticker style"
image = pipe(prompt, num_inference_steps=50).images[0]
image

"""# Step 6: Save the model to the Hugging face"""

import os
model_dir = "/content/lora_sticker_model"
print("exsit？", os.path.exists(model_dir))
if os.path.exists(model_dir):
    print("list：", os.listdir(model_dir))

!find /content -name "*.json" 2>/dev/null
!find /content -name "*.safetensors" 2>/dev/null

import json
import os

model_dir = "/content/lora_sticker_model"
config = {
    "base_model_name_or_path": "runwayml/stable-diffusion-v1-5",
    "revision": None,
    "rank": 8,
    "alpha": 16,
    "dropout": 0.1,
    "target_modules": ["to_q", "to_k", "to_v", "to_out.0"]
}
with open(os.path.join(model_dir, "adapter_config.json"), "w") as f:
    json.dump(config, f, indent=2)

print("adapter_config.json existed", model_dir)

from google.colab import files

files.download(os.path.join(model_dir, "pytorch_lora_weights.safetensors"))
files.download(os.path.join(model_dir, "adapter_config.json"))

import zipfile
import os
folder_path = "/content/lora_sticker_model"
zip_filename = "lora_sticker_model.zip"
with zipfile.ZipFile(zip_filename, "w", zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files in os.walk(folder_path):
        for file in files:
            file_path = os.path.join(root, file)
            arcname = os.path.relpath(file_path, folder_path)
            zipf.write(file_path, arcname)

from google.colab import files
files.download(zip_filename)

from diffusers import StableDiffusionPipeline
pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16).to("cuda")
pipe.unet.load_attn_procs("Lilian0703/sticker-lora-cartoon")
image = pipe("a cute dog, a sks style").images[0]
image